### ISSUE TITLE
[BUG] Inconsistent Event Time 

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#101]
System behaving as if this Event Time were May 5 (tomorrow). Event Time displayed is May 7.

![capture d ecran 2016-05-04 a 10 54 05 am](https://cloud.githubusercontent.com/assets/12802756/15023741/a2a74b08-11e6-11e6-959e-afe5b0ef81c2.png)
![capture d ecran 2016-05-04 a 10 53 49 am](https://cloud.githubusercontent.com/assets/12802756/15023740/a29f7dd8-11e6-11e6-8e77-00eeb53a3e3a.png)
![capture d ecran 2016-05-04 a 10 53 29 am](https://cloud.githubusercontent.com/assets/12802756/15023739/a29da972-11e6-11e6-8303-aee09497ef1e.png)

**Comment by virajmahesh** [comment]
I think there are two separate issues here.

1. The time the notification was generated. I'll do some more digging to see why this is the case. Did you edit the event date by any chance? That might be one reason for the discrepancy.

2. The time showing up in the Edit Event screen. This is a known bug. Right now, it just uses today's date  in the edit event screen. Working on a fix for this along with the other edit event issues you pointed out. Should be deployed in ~2 hours.

**Comment by mplauche** [comment]
It's not so much the fact that the notification time generated was 5/4 -
that seems okay, because that is today.
Its the fact that it says my event is tomorrow (the 5th).

I was playing around with edit events before this, including dates.

Thanks!

**Comment by virajmahesh** [comment]
Can you test it now? At the very least, edit event should now be consistent with what's being displayed elsewhere.

**Comment by mplauche** [comment]
Hi!

*  Edit Event is consistent with Display :)
*  When I copy an Event, in the Edit Event view, the Event time default of
copy is set to event time of original :)

But Timing still seems off by one day.

*  When I create an Event for May 6 (2 days from now), I get a reminder in
Notification feed that I have an event "tomorrow".
*  If I create an Event for May 5 (tomorrow), I don't get a reminder in
Notification feed that I have an event "tomorrow".



*  Also, when I create an Event by COPYing a previous event, I don't get a
reminder in Notification feed (I tested events for May 5 and May 6).

**Comment by mplauche** [comment]
Not sure if you are working on this already, but I just noticed that:

User gets a REMINDER (in Feed, not email) that their SHIFT is tomorrow

when they sign up for a shift on May 11, October 19, or any other date.

**Comment by virajmahesh** [comment]
Does it instantly generate the reminder? Or does it take 24 hours for the notification? A screenshot of the notification would be helpful.

**Comment by mplauche** [comment]
The REMINDER notification comes 2 seconds after the JOIN notification.

![capture d ecran 2016-05-05 a 10 00 51 am](https://cloud.githubusercontent.com/assets/12802756/15050375/49c83502-12a8-11e6-8a8e-471cac64db7b.png)

**Comment by virajmahesh** [comment]
We made some changes to try and fix this. Can you let us know if it's working now?

**Comment by mplauche** [comment]
It looks like Events that Aren't tomorrow are NOT generating reminders (hopefully until the day before) :)

But it looks like if I create an Event for tomorrow, it goes well, and does generate reminders, but then fails to display on the main screen:

![capture d ecran 2016-05-05 a 7 49 57 pm](https://cloud.githubusercontent.com/assets/12802756/15062980/eaae2150-12fa-11e6-8eb9-7d8324721d83.png)
![capture d ecran 2016-05-05 a 7 50 09 pm](https://cloud.githubusercontent.com/assets/12802756/15062982/efd21a38-12fa-11e6-95a7-e701818d57b1.png)
![capture d ecran 2016-05-05 a 7 50 19 pm](https://cloud.githubusercontent.com/assets/12802756/15062987/f7070a02-12fa-11e6-8f7a-79244db60dce.png)

**Comment by virajmahesh** [comment]
I think that's because the server is in UTC time, and it's already the next day in the UTC timezone. 

If you want, we can just display all events, or display events on the same day.
Which one would work better?

**Comment by mplauche** [comment]
Displaying same day events is the most useful, I think.

**Comment by mplauche** [comment]
On second thought, I don't know because I don't really understand the UTC timezone thing. 

But I know that if today is May 5 (and it is, from my perspective), I am going to want to see May 5 events and May 6 events and May 7 events and so on....

I don't need to see May 4 events anymore.

**Comment by virajmahesh** [comment]
Should be fixed now. Sorry for the delay!

**Comment by mplauche** [comment]
Okay getting better and better! Display of Today and Future events is perfect.
REMINDERS are still a little off, though.  Here are results from creating an event for Yesterday, Today, Tomorrow, and Mothers Day (2 days off). 

Tomorrow Event gets a reminder that event is tomorrow :)
Mothers Day does NOT get a reminder :)

Today gets a reminder that event is tomorrow :(
Yesterday gets a reminder that event is tomorrow :(

![capture d ecran 2016-05-06 a 7 48 52 am](https://cloud.githubusercontent.com/assets/12802756/15076556/2d477192-135f-11e6-9a84-dfab1164d17c.png)
![capture d ecran 2016-05-06 a 7 48 35 am](https://cloud.githubusercontent.com/assets/12802756/15076562/320a37e6-135f-11e6-86b7-3176ce375868.png)

**Comment by mplauche** [comment]
If the timezone is part of the problem, how hard is it to:
1. set the timezone to Pacific Standard Time
2. change the text everywhere from "tomorrow" to "happening soon" 

This last suggestion only works if we change ALL instances of saying "tomorrow" and it only really solves the problem for TODAY events (they can still have reminders saying "happening soon", even if they happened an hour ago. That's totally okay). 

But we would still have to fix the Yesterday Events getting reminders.  BUT I also think that is a bug that users could live with for the purposes of a beta-deploy. It all depends on just how hard it is to fix.

**Comment by virajmahesh** [comment]
1. has already been done and was required for the events to start showing up on the home page.
To make sure I understood it, the ideal solution is:
    a) Events in the past do not get any reminders
    b) All notifications that are today or tomorrow should say the event is "happening soon" instead of "tomorrow"
Both are do-able.
We can throw a third option into the mix:
   c) Prevent anyone from creating an event in the past. The earliest event starts today. This can even substitute (a) since if there aren't any past events in the system, we don't need to worry about a notification being generated for them.

Let me know what would work best for you!

**Comment by mplauche** [comment]
Okay sorry I wasn't clear - I was proposing either 1. or 2. as a possible solution. I didn't realize you had already implemented 1. 

So since I don't know anything about coding, let me just stick to the user perspective!

Ideal solution is:
a)
b) keep it "tomorrow", no need to change
c) prevent creating events in the past (i like this). But to be clear, I think it should be okay to create events for today.

But then we still need to fix the problems above:
Today gets a reminder that event is tomorrow :(    
 --> (possible solution: no reminder, or "happening soon")

Yesterday gets a reminder that event is tomorrow :(     (if c), this goes away)

**Comment by virajmahesh** [comment]
So which one do you prefer? No notifications for events today or "happening soon" only for events today.

**Comment by mplauche** [comment]
let's go with No notifications.

Thanks, so much, viral

**Comment by mplauche** [comment]
Just retested. 
EC can create events yesterday, today, and tomorrow. 
All result in notification to FEED and Email. 
The Tomorrow event additionally results in a reminder.  
The Yesterday event does not show up on the home page. 
![capture d ecran 2016-05-07 a 4 01 02 pm](https://cloud.githubusercontent.com/assets/12802756/15095099/4202d3c4-146d-11e6-8fc6-2054461010a8.png)
![capture d ecran 2016-05-07 a 4 00 08 pm](https://cloud.githubusercontent.com/assets/12802756/15095100/47da2acc-146d-11e6-9b8f-5ea9eb19a403.png)
![capture d ecran 2016-05-07 a 3 59 52 pm](https://cloud.githubusercontent.com/assets/12802756/15095102/4cb683ce-146d-11e6-8b9d-6032ef249552.png)
