### ISSUE TITLE
[BUG] COPY EVENT should generate Notification that an Event was Created

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#106]
When I use the "EVENT COPY" button, Its AWESOME! All the relevant things get copied, and all the irrelevant things do not (particular volunteers signed up for shifts). 

The only small thing missing from the Event Creators point of view is that by Copying, EC has just CREATED an Event.  EC should ideally get this same notification:

![capture d ecran 2016-05-05 a 10 07 55 am](https://cloud.githubusercontent.com/assets/12802756/15050533/4c9faa2a-12a9-11e6-8dbd-6fea326c610c.png)

**Comment by virajmahesh** [comment]
Was this resolved? Not sure if we fixed this.

**Comment by mplauche** [comment]
yes, it is working now.
