### ISSUE TITLE
[BUG] Cannot EDIT EVENT ISSUES

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#117]
When you create an event, whatever you specify for ISSUES (whether a particular value, such as 'community', or [none]), cannot be changed. 

Here I CREATE an EVENT with the ISSUE: Community

![capture d ecran 2016-05-12 a 12 45 45 pm](https://cloud.githubusercontent.com/assets/12802756/15228225/f4bd8150-183f-11e6-9f6a-6257efd0aef5.png)

Then I EDIT the EVENT, and I delete 'Community' and add 'Arts & Culture'

![capture d ecran 2016-05-12 a 12 46 20 pm](https://cloud.githubusercontent.com/assets/12802756/15228229/f84b6dfa-183f-11e6-9ba5-57033272866b.png)

When I return to view the Event, ISSUES reverts to original values, in this case 'Community'

![capture d ecran 2016-05-12 a 12 46 29 pm](https://cloud.githubusercontent.com/assets/12802756/15228231/fb73d9ea-183f-11e6-88dc-b16b91e53cc3.png)

**Comment by virajmahesh** [comment]
I was able to reproduce this. Will try and fix it, hopefully today, but by tomorrow night at the latest.

**Comment by virajmahesh** [comment]
This should be fixed now

**Comment by mplauche** [comment]
looks good.
