### ISSUE TITLE
[BUG] Can't delete SHIFT SKILLS

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#118]
If I Create a shift, and specify a skill, say "Media monitoring", 

![capture d ecran 2016-05-12 a 2 59 25 pm](https://cloud.githubusercontent.com/assets/12802756/15231835/544d1d30-1852-11e6-9d07-677deafbf5c3.png)

Then I go into Edit Shift to make changes:

![capture d ecran 2016-05-12 a 2 59 44 pm](https://cloud.githubusercontent.com/assets/12802756/15231842/57f3846a-1852-11e6-8f9e-529265be3b4e.png)

Here, I delete "Media Monitoring":

![capture d ecran 2016-05-12 a 2 59 58 pm](https://cloud.githubusercontent.com/assets/12802756/15231844/5b2eca04-1852-11e6-981c-6a78113adbfa.png)

But it still appears when I Save changes:

![capture d ecran 2016-05-12 a 3 00 10 pm](https://cloud.githubusercontent.com/assets/12802756/15231849/5db0fffe-1852-11e6-849f-3eaebbe7a0a6.png)

Adding a second skill works fine. 
Adding a second skill, then deleting the first, also works great. So it appears the system doesn't like a state in which there are NO skills specified in the Edit Skills screen.

**Comment by virajmahesh** [comment]
This should be fixed now

**Comment by mplauche** [comment]
good work!
