### ISSUE TITLE
Display Events on Home Page in Chronological Order

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#119]
It would be good to sort the Events by Date & Time so that when there are 20+ EVENTS, I am seeing the Events that will happen soonish at the top of the screen and the Events that are happening a few days from now further down towards the bottom of the screen.

**Comment by virajmahesh** [comment]
I know this was marked 'Nice to Have' but it was a really easy fix so I decided to knock it out. Right now the chronological ordering is hardcoded in, but I think this would fit into the sorting feature that we partially completed in the last iteration. Let me know if this works as intended!

**Comment by mplauche** [comment]
Looks like its working!
