### ISSUE TITLE
Replace SKILLS List with Custom List below

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#121]
[NNVolunteerActivitiesListSKILLS.docx.txt](https://github.com/virajmahesh/icsi-shift-scheduler/files/265244/NNVolunteerActivitiesListSKILLS.docx.txt)

**Comment by virajmahesh** [comment]
The skills now use this list.

**Comment by mplauche** [comment]
Looks good- thanks for customizing! 
The interface is a little weird - you have to type a letter to see the list and then its only partial (the items with that letter), so if you want to see the full list, you have to try it with a few different letters. I'm not sure if you have any ideas for that. 

I'm going to list it as an enhancement and just let users know about this idiosyncrasy in the meantime.

**Comment by mplauche** [comment]
When SKILLS for a SHIFT are displayed, it includes "/n", so a little hard to read. Can you clean up the display if you get a chance?
![capture d ecran 2016-05-15 a 7 11 49 pm](https://cloud.githubusercontent.com/assets/12802756/15278705/0edf8d60-1ad1-11e6-9404-56f3011d3da7.png)

**Comment by virajmahesh** [comment]
This should be fixed
