### ISSUE TITLE
 [CRITICAL] SIGN UP PAGE: Persist SKILLS & ISSUES values entered 

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#133]
SIGN UP PAGE: Persist SKILLS & ISSUES values entered if form submission gets rejected (for password too short, e.g.)

This will prevent lost work for a new user.

**Comment by virajmahesh** [comment]
This should be fixed now.

**Comment by mplauche** [comment]
great! Much better. 

Can we do the same for EDIT SIGN UP page?

**Comment by virajmahesh** [comment]
This should be fixed now.

**Comment by mplauche** [comment]
looks good!

**Comment by mplauche** [comment]
sorry, I thought i had tested this for EDIT SHIFT too, but maybe I missed it. 

I created a shift with skill 'programming':

![capture d ecran 2016-05-22 a 11 00 57 am](https://cloud.githubusercontent.com/assets/12802756/15455571/f1bb0386-200c-11e6-8da7-8e78b26bf6e9.png)


Then I EDITed that SHIFT by adding another skill and deleting the "ROLE" field (to test persist):

![capture d ecran 2016-05-22 a 11 01 11 am](https://cloud.githubusercontent.com/assets/12802756/15455573/0873309e-200d-11e6-92e8-fd6ea6545c27.png)


Two funny things happened: 1) SKILLS did not persist & 2) Role field did persist (to first value, not most recent value. 

![capture d ecran 2016-05-22 a 11 01 35 am](https://cloud.githubusercontent.com/assets/12802756/15455578/3081db9e-200d-11e6-9b72-bc7883ab519e.png)

**Comment by virajmahesh** [comment]
Fixed!
