### ISSUE TITLE
Tweaks to EVENT display: Change Black Bars

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#134]
In the black bars representing shifts, 
1. Make the black bars white (and corresponding text black). 
2. Change the representation of the red links "canvassing" to make it a clearer call-to-action. To go to the SHIFTS display to find out more about shifts. 

![capture d ecran 2016-05-16 a 9 48 28 am](https://cloud.githubusercontent.com/assets/12802756/15296703/68141b7e-1b4b-11e6-9c39-14cb7211a0bd.png)

**Comment by virajmahesh** [comment]
Is this now resolved since the bars are white?

**Comment by mplauche** [comment]
yes! i think this was a duplicate issue too.
