### ISSUE TITLE
Tweaks to the Event Creation screen: Time increments

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#141]
http://icsi-shift-scheduler-preview.herokuapp.com/events/new

Limit the selectable minutes to multiples of 15min

10:00
10:15
10:30
10:45

Make same change for EDIT EVENT screen.

**Comment by mplauche** [comment]
this for would be a big improvement to usability. are you tired of fixing little things yet? 

create events
edit events
create shifts
edit shifts

**Comment by virajmahesh** [comment]
Okay, I'll take a look at this!

**Comment by virajmahesh** [comment]
Fixed.

**Comment by mplauche** [comment]
ahhhhh. SO much better. thank you!
