### ISSUE TITLE
[CRITICAL] User needs ability to EDIT SIGN UP fields

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#148]
http://icsi-shift-scheduler-preview.herokuapp.com/users/sign_up
Currently, if the user wants to add a skill, or correct their user name, they can't edit any of these sign up fields once the form is submitted. 

I propose the following:
1. Top right of menu bar includes Name of User - Make that a link to an EDIT SIGNUP screen.
![capture d ecran 2016-05-16 a 10 37 59 am](https://cloud.githubusercontent.com/assets/12802756/15298060/551bf0c6-1b52-11e6-8972-b2fe7de23052.png)

2. EDIT SIGNUP screen looks very similar to SIGNUP screen.
Title is different (EDIT SIGN UP INFORMATION).
Text is populated with values user previously submitted.

**Comment by mplauche** [comment]
This one came up again when I tested Richard last night. He signed up, specified some skills, then after poking around the events, wanted to go back and modify his list of skills. Can we prioritize this one? 

Above is just a suggestion that seems like a quick fix. But really we just need to give the user some ability to go back and edit the info they put in during signup.

**Comment by virajmahesh** [comment]
This should work now

**Comment by mplauche** [comment]
This looks GREAT!

Small feature add involving skills below - not sure if it is hard to implement. 
When I EDIT SIGNUP, and add a skill "programming" to my profile (signup), I currently don't get any notifications about events that need that skill (but they do exist).
![capture d ecran 2016-05-20 a 7 58 05 am](https://cloud.githubusercontent.com/assets/12802756/15431950/05155a24-1e61-11e6-9d81-7de003acf9cd.png)
![capture d ecran 2016-05-20 a 7 57 53 am](https://cloud.githubusercontent.com/assets/12802756/15431953/08b57f38-1e61-11e6-9381-70679a388688.png)


If i create a shift that needs this skill AFTER editing my SIGNUP, it works fine, I DO get a notification that my skills are needed.

**Comment by virajmahesh** [comment]
Are you sure that you don't get notified for existing shifts after editing? I just tested it, and the in app notifications did get generated. The app won't generate fresh notifications if you've already been notified about a shift so maybe that's why no new notifications got generated?

**Comment by mplauche** [comment]
yes that's possible. Ill retest when I get a second.

**Comment by mplauche** [comment]
you are right! works great.
