### ISSUE TITLE
Delete all associated SHIFTS when you delete an EVENT. 

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#159]
We need to ensure that deleting an event triggers the deletion of the associated shifts too.

**Comment by virajmahesh** [comment]
This should be fixed. The way you can test this is:
1. Create an event
2. Create a shift
3. When viewing shift information, copy the shift URL.
4. Delete the event.
5. Now try and view the shift using the URL you copied. It should show you some error message.
