### ISSUE TITLE
Super User status for Madelaine

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#164]
email: plarlson@gmail.com
username: Madelaine

**Comment by virajmahesh** [comment]
I edited out the password for security reasons, but I'll generate the account for you before I hand it over for testing.

**Comment by virajmahesh** [comment]
This is ready for testing.
There was already an account with the email plarlson@gmail.com, so I promoted the existing account to superuser status. You should be able to login with that email. I can't see the password, so you might have to reset it if you can't access the account.

**Comment by mplauche** [comment]
ok - i need to really concentrate for this testing task so it might have to
wait until this evening.

**Comment by mplauche** [comment]
WOW! Transfer ownership? I love it. This works great. I tested it and found no problems, no bugs.
