### ISSUE TITLE
Events aren't completely deleted

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#172]
Hi V - A friend just caught this one - I think its new because I hadn't noticed it before. 

There are currently only two events:

![capture d ecran 2016-05-22 a 8 39 15 am](https://cloud.githubusercontent.com/assets/12802756/15454871/06d00208-1ff9-11e6-9ae6-6142eb87b1f7.png)

But if you sign up as a new user, you get notifications for lots of events that have been deleted:

![capture d ecran 2016-05-22 a 8 39 40 am](https://cloud.githubusercontent.com/assets/12802756/15454872/172f77c8-1ff9-11e6-9b77-8ca667593ead.png)

They still seem to have event pages, even though they don't show up on the main screen:

![capture d ecran 2016-05-22 a 8 39 58 am](https://cloud.githubusercontent.com/assets/12802756/15454879/27cc00c4-1ff9-11e6-9d39-1c84e53a0191.png)

**Comment by virajmahesh** [comment]
I think the issue is that the user is being notified about events in the past (judging by the date on the screenshot). So the real issue is that such notifications shouldn't occur. I'll fix this right now.

**Comment by virajmahesh** [comment]
This should be fixed now.
You can test it by creating an event in the past and then creating a new user.

**Comment by mplauche** [comment]
looks good. thanks!
