### ISSUE TITLE
Test Issue 

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#47]
Test Description of issue: Madelaine learns how to report issues in github.

**Comment by virajmahesh** [comment]
Thanks Madelaine. This looks good to me. Were you able to attach images to the issue as well?

**Comment by mplauche** [comment]
![capture d ecran 2016-04-13 a 9 18 41 am](https://cloud.githubusercontent.com/assets/12802756/14514006/87a8b256-01a1-11e6-86bd-ce4dae998aa2.png)

**Comment by mplauche** [comment]
oh yes, screen shots - I think that worked!
