### ISSUE TITLE
Description text boxes for EVENTS and SHIFTS need to be larger

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#65]
so you can write a paragraph of text, not just a line.

![capture d ecran 2016-04-17 a 5 28 09 pm](https://cloud.githubusercontent.com/assets/12802756/14591202/c9c21772-04c1-11e6-97fc-5509f72fc264.png)

**Comment by mplauche** [comment]
Text box is now paragraph size for CREATE EVENT, CREATE SHIFT, and EDIT SHIFT

Still too small for EDIT EVENT.

**Comment by virajmahesh** [comment]
Should be fixed now.
