### ISSUE TITLE
2/1 slots filled 

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#69]
I'm reporting this so I don't forget, but I don't think it needs to be resolved because we might change the "shift limit" part of creating events anyway.

This happened when the same user signed up for a shift twice.

![capture d ecran 2016-04-17 a 5 50 11 pm](https://cloud.githubusercontent.com/assets/12802756/14591356/e34c90fc-04c4-11e6-8272-d4f570792f35.png)

**Comment by mplauche** [comment]
See #90. 
This one showed up again but its hard to reduplicate.

**Comment by virajmahesh** [comment]
Accidently closed this, but it is fixed now.
