### ISSUE TITLE
Display shifts on white bar instead of black bar

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#71]
The simpler the UI, the better, for now.

**Comment by mplauche** [comment]
Viraj - if you have a second, could you change these black bars with white text to white boxes with black text? 

Now that the links are dark blue, its even harder to read the shifts than before. 

I hope that's an easy fix. I think it will make a big difference for usability.

**Comment by virajmahesh** [comment]
Fixed.

**Comment by mplauche** [comment]
thank you!
