### ISSUE TITLE
Feature add for Notification page - ability to delete (or 'hide' or 'mark as read') notifications

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#72]
Here is a very simple approach that would work for now.

![capture d ecran 2016-04-19 a 1 49 53 pm](https://cloud.githubusercontent.com/assets/12802756/14655127/c24dc458-0635-11e6-9e00-0c7d1224c42c.png)

But I'm open to something closer to fb if team prefers (but a little more complicated):
![capture d ecran 2016-04-19 a 12 24 19 pm](https://cloud.githubusercontent.com/assets/12802756/14652575/c0f9d29c-0629-11e6-8af5-cd5318d838dd.png)

**Comment by virajmahesh** [comment]
What exactly is April 4,2016, 10:38 PM? Is that the date and time the user signed up for the shift?

**Comment by mplauche** [comment]
good question - yes. Its the date of the Action (not the date of Event or Shift). 
I wrote it really tiny above.

**Comment by mplauche** [comment]
Is there any chance you are free to talk (20 min or so)?
I've got an hour just now and also tomorrow I have lots of time.

I just have some questions about what of all the stuff we discussed is
feasible in 2 weeks.
