### ISSUE TITLE
[BUG] Notifications are not working

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#87]
currently I don't receive a notification either by email or in my feed when I:
1. JOIN a shift
2. LEAVE a shift
3. CREATE an event
4. someone SIGNS UP for my event

or for any other reason, with one exception:
A notification for "your event is happening tomorrow" does appear in Notifications, but not Email

**Comment by mplauche** [comment]
Wed morning UPDATE: 
Event creator gets Email messages regarding people leaving and joining shifts :)
Event creator gets message in Feed reminding them about an event tomorrow :)

?User does not get message in Feed reminding them about a shift they are signed up for tomorrow :( (this is hard to test, so I'm not sure, but I don't think this is working)
Event creator does not get messages in their Feed regarding people leaving and joining shifts :(
User does not get Email messages when they leave, join or are removed from a shift. :(
User does not get messages in their Feed when they leave, join, or are removed from a shift :(
Email message text has not yet been updated to match mockup document :(
Event Creator does not get message in Feed if they create an event. :(
Event Creator does not get Email message if they create an event. :(

**Comment by kaloncheung124** [comment]
We have not implemented users getting notifications when they leave or join a shift. We instead notify the _event creator_ as stated in [your Google Doc for Iteration 3](https://docs.google.com/document/d/1KvrRgiqV1Mm1-s8tiXSfjfZKXv4L0bHxO9e_qSceEcA/edit#heading=h.ilg6m0c3a31p). If you wish to also notify the user who joins or leaves, I can work on that and it shouldn't take long.

The feed notification (email hasn't been implemented yet) for removing users from a shift should work. When a user is removed from a shift, that removed user receives a notification (I just tested it, it may not have been implemented earlier).

We also haven't implemented the event creator getting a notification when they create an event. But this also shouldn't take long and I can implement it.

Thanks for the feedback!

**Comment by mplauche** [comment]
That would be great, if you could implement the :( above, even if they didn't show up in Iteration 3 requests. Thank you so much! 

I tested the feed and yes, 

User gets a message in feed when they are removed from a shift. :)

**Comment by virajmahesh** [comment]
User does not get Email messages when they leave, join or are removed from a shift.
Email message text has not yet been updated to match mockup document

Barring some minor typos while copying the text from the mocks, these two issues should be fixed now.
Notifications are always sent in pairs, to the event creator and the user, so it's a bug if only one of them gets a notification for something and the other doesn't.

One of the emails wasn't in the mocks so I improvised a little, using the language of the other emails. I think it's the email to the event creator when they drop someone from a shift. Let me know if something is wrong with the way this is worded.

**Comment by mplauche** [comment]
Really looking good. I think we are almost done! The only thing I noticed missing was:

Event Creator does not get Email when they CREATE an Event.

The wording is also all fine (thanks for improvising), and really adds to the app as far as supporting the user to remember and keep track of what is happening when. There is one thing that is missing that would really help volunteers coordinate with one another, and that is the Event Creator's (EC) email address for the following cases:

User needs EC's address in Email message when User JOINS
User needs EC's address in Email message when User is DROPPED by EC
User needs EC's address in Email message when User is REMINDED about upcoming shift.

Check out last line below:
![capture d ecran 2016-05-05 a 9 47 56 am](https://cloud.githubusercontent.com/assets/12802756/15050077/88a552fc-12a6-11e6-84f8-f4c5e3f7ef61.png)

**Comment by virajmahesh** [comment]
Fixed User needing EC's address in email message in all scenarios.

Reminder email still isn't implemented. Will work on this.
I can't find a mock for what the Create Event email should look like. Is it in the Google Drive folder?

**Comment by mplauche** [comment]
Thanks! How about:

To: EC
From: Uprise Notifications
Subject: You have created a new event. 

You have created the following event: 

Debate Watch Party     Oakland, CA
April 12, 2016  8pm -12pm

**Comment by virajmahesh** [comment]
Both reminder and create emails should work now.

**Comment by mplauche** [comment]
oh sorry- I was a little too excited. 

We are missing the time "8pm - 12pm" 
in the email text.

**Comment by virajmahesh** [comment]
Should be fixed now.

**Comment by mplauche** [comment]
looks great!

comma after the day of the month, would make it just a bit more legible,
but I can live with it as is.

"May 19, 2016"

Thanks for the hard work,
Madelaine

**Comment by virajmahesh** [comment]
Inserted the comma.
