### ISSUE TITLE
[BUG] No ability to edit TIME for EVENT

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#89]
An Event time is displayed for each Event, but there is not a way to edit the time in the Edit Event Screen:

![capture d ecran 2016-05-02 a 8 57 27 am](https://cloud.githubusercontent.com/assets/12802756/14959374/edc3b580-1043-11e6-9f1c-3251cfa0b4fd.png)

**Comment by mplauche** [comment]
Also no ability to Edit ISSUES of an EVENT

**Comment by virajmahesh** [comment]
Should be fixed now.
