### ISSUE TITLE
[BUG] COPY EVENT needs to copy the SHIFTS of that EVENT

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#94]
Here is an EVENT complete with SHIFTS. 
![capture d ecran 2016-05-02 a 9 31 10 am](https://cloud.githubusercontent.com/assets/12802756/14960246/a070f982-1048-11e6-8719-3f656be042fe.png)

When I COPY EVENT, the SHIFTS are not copied. 

![capture d ecran 2016-05-02 a 9 27 19 am](https://cloud.githubusercontent.com/assets/12802756/14960238/8bcf12a2-1048-11e6-91bf-ba6755d22a3e.png)

**Comment by virajmahesh** [comment]
Should be fixed now.
